name: "Terraform static validation"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd staging
      - run: terraform fmt -check
      - run: terraform validate